### ISSUE TITLE
Error while running the demo.py on Custom Dataset

### ISSUE THREAD

**Issue by sunjeet95** [mlzxy/devit#16]
So I have a custom dataset and few labels belonging to just one class. I also created the prototypes of that class using the build_prototype.ipynb but when iItry using the demo.py to run the model on my custom images and using the custom prototypes I get the following errors:

```
Traceback (most recent call last):
  File "./demo/demo.py", line 262, in <module>
    fire.Fire(main)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./demo/demo.py", line 212, in main
    output = model(batched_inputs)[0]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/viztel/roller-grill-ocr/models/label-detector/devit/./demo/../detectron2/modeling/meta_arch/devit.py", line 1168, in forward
    other_classes = interpolate(other_classes, self.T, mode='linear') # (Nxclasses) x spatial x T
  File "/workspace/viztel/roller-grill-ocr/models/label-detector/devit/./demo/../detectron2/modeling/meta_arch/devit.py", line 86, in interpolate
    return F.interpolate(seq, T, mode=mode) 
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 3945, in interpolate
    return torch._C._nn.upsample_linear1d(input, output_size, align_corners, scale_factors)
RuntimeError: Input and output sizes should be greater than 0, but got input (W: 0) and output (W: 128)
```

**Comment by sunjeet95** [comment]
Got the solution from a different closed issue.
