### ISSUE TITLE
How to train custom datasets

### ISSUE THREAD

**Issue by xfby2016** [mlzxy/devit#4]
Excellent job, I want to use it for object detection in specific datasets, but how to prepare my own dataset or what steps should I follow?
Thank you again！

**Comment by harrytrinh96** [comment]
same question

**Comment by mlzxy** [comment]
I guess you could first organize your data in COCO format, then register your coco json in this file: https://github.com/mlzxy/devit/blob/main/detectron2/data/datasets/builtin.py. Regarding COCO JSON format, you could take this https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/003.ipynb as reference. 

Then, prepare class prototypes for your classes, like https://github.com/mlzxy/devit/blob/main/demo/build_prototypes.ipynb. Probably the background prototypes can be reused because background classes are similar. Regarding the RPN, you could consider reuse the LVIS RPN from RegionCLIP like I did, or retrain COCO RPN from scratch using all 80 classes. This script https://github.com/mlzxy/devit/blob/main/scripts/train_rpn.sh can be the entry point. 

Or you could use some existing class-agnostic proposal extractor, slower but far more accurate, like  this paper https://arxiv.org/abs/2111.11430

**Comment by YELKHATTABI** [comment]
Hello :wave: Great paper and impressive results ! 
I am trying to test the ability of the model for few shot learning (with a small dataset) and trying to wrap my head around what to change in order to do this.

What I have done so far : 
- Formatted my dataset in COCO format, added 2 json files to `datasets/coco/annotations/` one for train and one for val
- Added the images to `datasets/coco/` as mini_coco
- Added new keys and elements to the https://github.com/mlzxy/devit/blob/main/detectron2/data/datasets/builtin.py so now it looks like this 
```
_PREDEFINED_SPLITS_COCO["coco"] = {
    "coco_2014_train": ("coco/train2014", "coco/annotations/instances_train2014.json"),
    "coco_2014_val": ("coco/val2014", "coco/annotations/instances_val2014.json"),
    "coco_2014_minival": ("coco/val2014", "coco/annotations/instances_minival2014.json"),
    "coco_2014_minival_100": ("coco/val2014", "coco/annotations/instances_minival2014_100.json"),
    "coco_2014_valminusminival": (
        "coco/val2014",
        "coco/annotations/instances_valminusminival2014.json",
    ),
    "coco_2017_train": ("coco/train2017", "coco/annotations/instances_train2017.json"),
    "coco_2017_val": ("coco/val2017", "coco/annotations/instances_val2017.json"),
    "coco_2017_test": ("coco/test2017", "coco/annotations/image_info_test2017.json"),
    "coco_2017_test-dev": ("coco/test2017", "coco/annotations/image_info_test-dev2017.json"),
    "coco_2017_val_100": ("coco/val2017", "coco/annotations/instances_val2017_100.json"),
    "coco_mini_train" : ("coco/mini_coco", "coco/annotations/mini_coco_train.json"),
    "coco_mini_val" : ("coco/mini_coco", "coco/annotations/mini_coco_val.json"),
}
```

Now I am trying to use this script to generate prototypes based on the boxes of annotations that I have in my training set : 
https://github.com/mlzxy/devit/blob/main/tools/extract_instance_prototypes.py but I am not sure how to fetch the name of the dataset, is it the same as the keys of datasets in `builtin.py` ? Did I miss anything?

Cheers

**Comment by Anymake** [comment]
> Hi @YELKHATTABI
> 
> After modifying `builtin.py`, you could set a breakpoint at https://github.com/mlzxy/devit/blob/main/detectron2/data/datasets/builtin.py#L327 and use detectron2 dataset interface (https://detectron2.readthedocs.io/en/stable/tutorials/datasets.html#metadata-for-datasets) to inspect the meta data of your dataset, e.g., classes. If you are not sure the name of the class, the function `DatasetCatalog.list()` may help you.
> 
> Note that I hardcode the class names of COCO/LVIS in https://github.com/mlzxy/devit/blob/main/lib/categories.py and use them in https://github.com/mlzxy/devit/blob/main/detectron2/modeling/meta_arch/devit.py#L792 and https://github.com/mlzxy/devit/blob/main/tools/train_net.py#L95C44-L95C44 to separate base / novel classes. You may also need to add your classes split to `categories.py`.
> 
> Regarding the prototypes extraction, if the `extract_instance_prototypes.py` doesn't work (I write that a long time ago), you could always just extract and crop some features and compute the mean (like in the demo jupyter notebook).
> 
> Note that for bounding box annotation, you need to have a little more shot, for example 5-shot at least (which I guess is ok), in 1-shot bounding box performance is way lower than using instance masks.

This method of directly modifying COCO seems a bit complicated. Is there any other method to register a new dataset just as COCO/LVIS ?

**Comment by Kay545** [comment]
Great idea! I use my own data set and place it in coco format without changing the config file. I change the name of the json file trained by my own data set to fs_coco14_base_train. An error will be reported. Do you know what is going on?thanks

The following is the error message：
[12/20 07:35:24 detectron2]: Full config saved to output/train/few-shot/shot-10/vitl/config.yaml
[12/20 07:35:24 d2.utils.env]: Using a generated random seed 24627623
('fs_coco_test_all',)
Traceback (most recent call last):
  File "/content/devit/tools/train_net.py", line 202, in <module>
    launch(
  File "/content/devit/tools/../detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/content/devit/tools/train_net.py", line 190, in main
    trainer = Trainer(cfg)
  File "/content/devit/tools/../detectron2/engine/defaults.py", line 379, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/content/devit/tools/../detectron2/engine/defaults.py", line 550, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/content/devit/tools/../detectron2/config/config.py", line 192, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/content/devit/tools/../detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/content/devit/tools/../detectron2/data/build.py", line 342, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/content/devit/tools/../detectron2/data/build.py", line 229, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/content/devit/tools/../detectron2/data/build.py", line 229, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/content/devit/tools/../detectron2/data/catalog.py", line 58, in get
    return f()
  File "/content/devit/tools/../detectron2/data/datasets/coco.py", line 500, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/content/devit/tools/../detectron2/data/datasets/coco.py", line 69, in load_coco_json
    coco_api = COCO(json_file)
  File "/usr/local/lib/python3.10/dist-packages/pycocotools/coco.py", line 86, in __init__
    self.createIndex()
  File "/usr/local/lib/python3.10/dist-packages/pycocotools/coco.py", line 95, in createIndex
    imgToAnns[ann['image_id']].append(ann)
KeyError: 'image_id'

**Comment by Kay545** [comment]
@mlzxy

**Comment by mlzxy** [comment]
Hi, sorry for my late reply. Kind of busy recently. I would suggest not directly modifying coco, but packing your dataset in the COCO format. 

Regarding that dataset repacking, I suggest two approaches: 

1. Take this notebook  https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/003.ipynb  as a reference to reorganize your dataset. The output dataset format shall be correct as long as the procedure is followed. I took this approach but it is a bit cumbersome. 

2. Use this tool, https://github.com/waspinator/pycococreator . It is much easier but I haven't used it for a long time. So it may not work. 

@Kay545 It appears that your annotation object lacks the image id field. Try to use the `pycococreator` tool, it shall generate the data with the right format.

**Comment by Kay545** [comment]
@mlzxy Thank you for your thoughtful suggestions and the provided resources. I appreciate your insights into repacking the dataset without directly modifying COCO. I will explore both approaches you mentioned, taking into consideration the notebook you shared and the pycococreator tool. 

Best regards.

**Comment by curious-ai-developer** [comment]
@mlzxy @Kay545 
Hi!
  Thanks for your help. I want to apply this method on my custom dataset. I have 5 images for one new object. I built yrt_prototypes.pth with demo/build_prototypes.ipynb to get prototypes similar to ycb_prototypes.pth
I ran the demo successfully. Do I need to change the weights? How do I train to get my desired weights? I changed category_space="demo/yrt_prototypes.pth" in demo.py 
what other steps do I take to run this updated demo.py to find my new object in a test image in input folder? 
I made a json file with coco format for my dataset by using labelme for image annotation and labelme2coco to convert it to coco json format but I never used it because I don't know how.

**Comment by mlzxy** [comment]
@curious-ai-developer  The new prototype file already include the class weights for your new categories. What the demo.py does is to replace the class weights in loaded checkpoints with `ycb_prototypes.pth`.  You don't need to change other weights.

**Comment by curious-ai-developer** [comment]
> @curious-ai-developer The new prototype file already include the class weights for your new categories. What the demo.py does is to replace the class weights in loaded checkpoints with `ycb_prototypes.pth`. You don't need to change other weights.

@mlzxy 
Many thanks for your response. As I said I trained and got my new object prototype as ycb_prototypes.pth and replaced it with the previous one in demo folder. I got this error:

/content/devit/demo/../detectron2/modeling/meta_arch/devit.py:475: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  p1, p2 = torch.load(class_prototypes_file[0]), torch.load(class_prototypes_file[1])
/content/devit/demo/../detectron2/modeling/meta_arch/devit.py:536: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  bg_protos = torch.load(bg_prototypes_file)
/content/devit/demo/demo.py:186: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(model_path, map_location=device)['model'])
/content/devit/demo/demo.py:191: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  category_space = torch.load(category_space)
/usr/local/lib/python3.10/dist-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/content/devit/demo/../detectron2/modeling/meta_arch/devit.py:1018: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):
Traceback (most recent call last):
  File "/content/devit/demo/demo.py", line 262, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/devit/demo/demo.py", line 212, in main
    output = model(batched_inputs)[0]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/devit/demo/../detectron2/modeling/meta_arch/devit.py", line 1184, in forward
    other_classes = interpolate(other_classes, self.T, mode='linear') # (Nxclasses) x spatial x T
  File "/content/devit/demo/../detectron2/modeling/meta_arch/devit.py", line 102, in interpolate
    return F.interpolate(seq, T, mode=mode) 
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 4559, in interpolate
    return torch._C._nn.upsample_linear1d(
RuntimeError: Input and output sizes should be greater than 0, but got input (W: 0) and output (W: 128)

I didn't use my new object coco format json dataset for obtaining ycb_prototypes.pth, I just ran demo/build_prototypes.ipynb with 5 images of my new object with their binary masks.

**Comment by kirillsemenov1314** [comment]
Hi @mlzxy,

First of all, thanks for the excellent explanations and resources shared so far!

I’ve successfully constructed a dataset and built prototypes for three classes on which I want to fine-tune the model. However, I have a few questions:

Where should I register the prototypes for these classes? Are they explicitly needed during training, or can they be inferred from the data during fine-tuning?

Do I need to fune tune the model with task=fsod on these three classes?

My goal is to fune tune the model on these three classes and later perform inference on other unseen classes, for which I will construct new prototypes.
Any clarification on these points would be greatly appreciated! Thank you!

**Comment by mlzxy** [comment]
@kirillsemenov1314 Suppose your dataset is already registered into detectron2, then I think you need to change

1. https://github.com/mlzxy/devit/blob/main/lib/categories.py  This file specifies the classes of COCO, LVIS, and VOC. You may need to add yours. Note that I have separate SEEN CLS and ALL CLS (SEEN + UNSEEN) in this file. Because the convention of FSOD assumes base classes (SEEN) have lots of images, and novel classes have K images each (K-shot). But in your case, if I understand correctly, you have 3 base classes, but novel classes have no images during training. I think maybe just set SEEN and ALL CLS to be the same. 

2. https://github.com/mlzxy/devit/blob/main/configs/open-vocabulary/coco/vitl.yaml#L3C3-L3C19  In the config file, change the CLASS_PROTOTYPES line, to point to your prototype file. Then, change `DATASETS.TRAIN/TEST` to your dataset. 

Btw, my refactored implementation gives better performance, as suggested in the README. If you want to train from scratch, you can try that. You can also try different RPN networks, like the one from COCO or LVIS. LVIS one may be better if your scenario has lots of crowded small objects.

**Comment by kirillsemenov1314** [comment]
@mlzxy Thank you for detailed explanations,

I noticed you pointed to the open-vocabulary config (vitl.yaml) for fine-tuning when using image-based prototypes for novel classes. Could you clarify:

- Why is the open-vocabulary config preferred for this scenario?

- Is there a difference between using the open-vocabulary config versus the few-shot (fsod) config when fine-tuning with image-based prototypes?

- Should I use the few-shot config (vitl_shot10.yaml) with task=fsod instead, or stick with the open-vocabulary one?

Looking forward to your guidance—thank you for your time!

Best regards

**Comment by mlzxy** [comment]
@kirillsemenov1314  Since this method use images to represent category instead of texts, so fsod and open-voc are practically the **same** here. But the open-vocabulary configs (COCO and LVIS) may have better region-proposal networks than the FSOD ones because FSOD settings use older datasets (e.g. COCO14, Pascal VOC). That is why I recommend to start with open-vocabulary config.

**Comment by kirillsemenov1314** [comment]
@mlzxy Thank you for your earlier guidance! I’ve been following the instructions to fine-tune the model using image-based prototypes and the open-vocabulary config (vits.yaml). However, I’ve been encountering persistent errors during training and would appreciate your advice.

### Steps I’ve Taken
1.  Dataset Setup:

- Registered my dataset as my_custom_dataset_train and my_custom_dataset_test.

2. Updated categories.py:

- Set COCO_OVD to my_custom_dataset_train.
- Updated SEEN_CLS_DICT and ALL_CLS_DICT for COCO_OVD to include my three classes: ["class_1", "class_2", "class_3"].

3. Modified Config (configs/open-vocabulary/coco/vits.yaml):

- Set CLASS_PROTOTYPES to the prototypes generated using build_prototypes.ipynb.

- Updated DATASETS section to point to my custom datasets:

```
DATASETS:
  TRAIN: ("my_custom_dataset_train",)
  TEST: ("my_custom_dataset_test",)
```
- Set topk to 3 in the config, matching my three base classes.

4. Training Command:

- Ran the following command:
`vit=s task=ovd dataset=coco bash scripts/train.sh`

### Issue Encountered
During training (around iteration 66), I consistently encounter this error:
`RuntimeError: DataLoader worker (pid XXXX) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.`

### Debugging Attempts

- Updated detectron2/config/defaults.py to reduce batch size and dataloader workers:

```
_C.DATALOADER.NUM_WORKERS = 2 (from 4).
_C.MODEL.RPN.BATCH_SIZE_PER_IMAGE = 16 (from 256).
_C.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 16 (from 512).
_C.DE.RCNN_BATCH_SIZE = 16 (from 128).
```

Despite these changes, the same error persists.

Questions

- What might be causing this issue with the DataLoader or shared memory, and how can I debug it further?

- Is there anything specific to open-vocabulary configurations or custom dataset setups that I might have overlooked?

- Would further adjustments to batch sizes or shared memory limits potentially resolve the issue?

Thank you for your time and support!
Kirill

**Comment by mlzxy** [comment]
@kirillsemenov1314 This looks like a lack-of-system-resource issue, like memory, file descriptors alike. Usually reducing the number of workers can help. Another thing is that you can run `ulimit -a` in your terminal to check the current system limit. It is possible that your machine has enough resource, but it by default imposes a limit per process. 

Usually what I do is to lift this limit by 

```
ulimit -n unlimited
ulimit -u unlimited
ulimit -s unlimited
```
(change unlimited to any large enough number that your system allow).

**Comment by kirillsemenov1314** [comment]
Hi @mlzxy,

Thank you for your earlier response and guidance regarding the choice of configurations. I managed to fine-tune the model successfully following the steps you suggested. However, I’m encountering an issue when trying to load the fine-tuned model for inference.

1. I used the open-vocabulary COCO config (vits.yaml) for fine-tuning.

2. The final model checkpoint was saved during fine-tuning at: `output/train/open-vocabulary/coco/vits/model_final.pth.`

### Inference Attempt
To load the model for inference, I followed this setup:
```
config_file= "configs/open-vocabulary/coco/vits.yaml"  # Config used for training
rpn_config_file="configs/Base-RCNN-C4.yaml"           # Referenced RPN config from COCO config (vits.yaml): _BASE_: "../../Base-RCNN-C4.yaml"
model_path="output/train/open-vocabulary/coco/vits/model_final.pth"  # Fine-tuned model checkpoint

config = get_cfg()
config.merge_from_file(config_file)
config.DE.OFFLINE_RPN_CONFIG = rpn_config_file
config.MODEL.MASK_ON = True
config.freeze()

# Build model
model = Trainer.build_model(config).to(device)
model.load_state_dict(torch.load(model_path, map_location=device)['model'])

```
### Error Encountered
```
When loading the model weights, I encountered the following error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[107], line 16
     14 print("device:", device)
     15 model = Trainer.build_model(config).to(device)
---> 16 model.load_state_dict(torch.load(model_path, map_location=device)['model'])
     17 model.eval()
     18 model = model.to(device)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1671, in Module.load_state_dict(self, state_dict, strict)
   1666         error_msgs.insert(
   1667             0, 'Missing key(s) in state_dict: {}. '.format(
   1668                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   1670 if len(error_msgs) > 0:
-> 1671     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1672                        self.__class__.__name__, "\n\t".join(error_msgs)))
   1673 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for OpenSetDetectorWithExamples:
	Missing key(s) in state_dict: "mask_intra_dist_emb.weight", "mask_intra_dist_emb.bias", "mask_bg_dist_emb.weight", "mask_bg_dist_emb.bias", "mask_feat_compress.0.weight", "mask_feat_compress.0.bias", "mask_feat_compress.1.weight", "mask_feat_compress.1.bias", "mask_feat_compress.2.weight", "mask_feat_compress.2.bias", "fc_init_mask.weight", "fc_init_mask.bias", "mp_layers.0.0.weight", "mp_layers.0.0.bias", "mp_layers.0.1.weight", "mp_layers.0.1.bias", "mp_layers.1.0.weight", "mp_layers.1.0.bias", "mp_layers.1.1.weight", "mp_layers.1.1.bias", "mp_layers.2.0.weight", "mp_layers.2.0.bias", "mp_layers.2.1.weight", "mp_layers.2.1.bias", "mp_layers.3.0.weight", "mp_layers.3.0.bias", "mp_layers.3.1.weight", "mp_layers.3.1.bias", "mp_layers.4.0.weight", "mp_layers.4.0.bias", "mp_layers.4.1.weight", "mp_layers.4.1.bias", "mp_out_layers.0.weight", "mp_out_layers.0.bias", "mp_out_layers.1.weight", "mp_out_layers.1.bias", "mp_out_layers.2.weight", "mp_out_layers.2.bias", "mp_out_layers.3.weight", "mp_out_layers.3.bias", "mp_out_layers.4.weight", "mp_out_layers.4.bias", "mask_deconv.0.weight", "mask_deconv.0.bias", "mask_deconv.1.weight", "mask_deconv.1.bias", "mask_predictor.weight", "mask_predictor.bias". 
```

- Am I using the correct configuration for inference (vits.yaml + Base-RCNN-C4.yaml)?

- Is there something I might have missed during fine-tuning or inference setup?

- Would you recommend any specific adjustments to the configuration or the model-loading procedure?

Looking forward to your advice—thank you for your time and help!
Best Regards,
Kirill

**Comment by mlzxy** [comment]
Hi,  maybe you can set config.MODEL.MASK_ON = False.  When this is True,
it tries to load weights for instance segmentation masks. So errors will be
raised if your checkpoint do have them.

Best,
Xinyu

**Comment by gxk666** [comment]
@mlzxy I'm now trying to create my own dataset for training and validation, I'm starting with a very small dataset and I've set up three standard folders, train, val, and 10shot. Then I wrote a file similar to builtin.py builtin_mydatasets.py to register my dataset, the code is as follows:
`import os
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.data.datasets import load_coco_json
_PREDEFINED_SPLITS_MYDATA = {
    "mydata": {
        "doudou_2025_train": ("Doudou/train2025", "Doudou/annotations/train.json"),
        "doudou_2025_val": ("Doudou/val2025", "Doudou/annotations/val.json"),
        "fs_doudou_trainval_novel_5shot": ("10shot/images", "10shot/annotations/10shot.json"),
    }
}

def register_all_mydata(root):
    for key, (image_root, json_file) in _PREDEFINED_SPLITS_MYDATA["mydata"].items():
        json_file_path = os.path.join(root, json_file)
        image_root_path = os.path.join(root, image_root)
        
        DatasetCatalog.register(
            key,
            lambda json_file=json_file_path, image_root=image_root_path, key=key: load_coco_json(
                json_file, image_root, {}, key
            )
        )   
        MetadataCatalog.get(key).set(
            json_file=json_file_path,
            image_root=image_root_path,
            evaluator_type="coco", 
            thing_classes=["insulator string", "broken", "flashover", "missing"]
        )

_root = os.getenv("MY_DATASETS", "datasets")
register_all_mydata(_root)

if __name__ == "__main__":
    from detectron2.data import DatasetCatalog
    print("已注册的数据集：", DatasetCatalog.list())`

Then, I put a piece of code at the end of the categories.py to define my class, which goes like this:

`DOUDOU = "Doudou"

DOUDOU_BASE_CLASSES = ["insulator string"] 
DOUDOU_NOVEL_CLASSES = ["broken", "flashover","missing"]  

DOUDOU_ALL_CLASSES = DOUDOU_BASE_CLASSES + DOUDOU_NOVEL_CLASSES

SEEN_CLS_DICT[DOUDOU] = DOUDOU_BASE_CLASSES
ALL_CLS_DICT[DOUDOU] = DOUDOU_ALL_CLASSES
#############################################################`
So I tried to run extract_instance_prototypes.py using the fs_doudou_trainval_novel_5shot in the code to create a prototype of the new class, specifically, I put 15 images in this callup file, divided into three categories of 5 images each, and annotated each image. But when I build the prototype, an assertion error occurs. I used the python3 ./tools/extract_instance_prototypes.py --fs_doudou_trainval_novel_5shot --model vits14 command to run the program for prototype extraction.
Hope you can have time to take a look at it for my questions.Thank you!

**Comment by mlzxy** [comment]
@gxk666  I recommend you directly average the "mean mask features" as the prototype. By "mean mask features", you can refer to this line: https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/tools/extract_instance_prototypes.py#L236 . This line averages the patch features at the instance location. If you have multiple shots, just average the mean mask feature at each instance. 


The extract instance prototype uses sinkhorn and augmentation, which I later found not very impactful. Of course the implementation itself involves more complexity and could causes more efforts to work with (like you are experiencing).  

Just computing mean features work equally or even a tiny bit better, and very simple. You can find a similar procedure in https://github.com/mlzxy/devit/blob/main/demo/build_prototypes.ipynb.

**Comment by gxk666** [comment]
> [@gxk666](https://github.com/gxk666) 我建议你直接对“平均掩码特征”进行平均，作为原型。“平均掩码特征”可以参考以下代码：
> 
> [devit/工具/extract_instance_prototypes.py](https://github.com/mlzxy/devit/blob/9cab390fbe78b3bc8d62c224411dce1c71056cf9/tools/extract_instance_prototypes.py#L236)
> 
> 第 236 行 [9cab390](/mlzxy/devit/commit/9cab390fbe78b3bc8d62c224411dce1c71056cf9)
> 
>  avg_patch_token  = ( bmask  *  patch_tokens ) .flatten ( 1 ) .sum ( 1 ) /bmask.sum  ( )​​
> 这条线会计算实例位置上 patch 特征的平均值。如果有多个镜头，只需计算每个实例上 mask 特征的平均值即可。
> 提取实例原型使用了 sinkhorn 和 augmentation，后来我发现效果并不好。当然，实现本身会更加复杂，可能需要投入更多精力（就像你正在经历的那样）。
> 
> 只需计算平均特征，效果同样好，甚至略胜一筹，而且非常简单。您可以在https://github.com/mlzxy/devit/blob/main/demo/build_prototypes.ipynb找到类似的步骤。

@mlzxy Hello, when training a custom dataset, in the step of building a class prototype, a file like fewshot.py in the lib is involved. I'd like to ask if it's necessary for me to build such a file for my own dataset to support few-shot learning?
